services:
  my-web:
    container_name: my-web
    image: gjwoo96/deploytest:latest
    ports:
      - 12345:80
      
  watchtower:
    container_name: my-watchtower
    image: containrrr/watchtower
    environment:
      TZ: Asia/Seoul
      WATCHTOWER_POLL_INTERVAL: 30
      WATCHTOWER_CLEANUP: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
